apiVersion: skaffold/v4beta7 
kind: Config
build:
  artifacts:
  - image: salman1091/hello-world-image
    context: .
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - Kuberenetes/*.yaml
