apiVersion: skaffold/v2beta18
kind: Config
build:
  artifacts:
  - image: hello-world-image
    context: .
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - Kuberenetes/*.yaml
