apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app01
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
  externalIPs: # Add this section to specify your host's IP address
    - 192.168.100.11 
